### ISSUE TITLE
Exposed source code

### ISSUE THREAD

**Issue by Kasslim** [dnreyes/CMPM146-Game-AI-Final#1]
Hello @dnreyes ! I'm the author of "Kasslim's Mazes". I spent many days creating this mod and never intended for the sources to be out in the open. But they are present in multiple locations in your repo.

Could you please either add information to your repostiory (in code files and readme) crediting me as the original author of all code in */brandsma/kas/mazemod/ *, or private/remove my code/this repository? (Depending what amount of effort you want to put in.) Feel free to make other suggestions too.

Please respond ASAP.

My copyright notice can be found on:
https://web.archive.org/web/20171224122604/https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1292566-kasslims-mazes

**Comment by alisiamartz** [comment]
Hi there, thanks for reaching out! This was for a **failed** CS project final. As this was over 4 years ago, we have no problem deleting your code that is present in the project.

Delmy, I am currently deleting all the bits of code. Feel free to archive the entire project. Don't think we need it anymore. :)

**Comment by Kasslim** [comment]
Thank you so much for responding so quickly! Sorry to hear about the project.

I can see you deleted the main src folder, can you also grab:
CMPM146-Game-AI-Final/mcp/temp/src/minecraft/brandsma/kas/mazemod/
?

Thanks again and have a good one guys!

**Comment by alisiamartz** [comment]
Done. Let me know if there's anything else you can spot. 

Thanks! You too.
